In [57]:
import keras
import numpy as np
from keras.datasets import mnist

In [219]:
img_size = 28
img_flat = img_size **2
num_classes = 10

(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train = x_train.reshape((-1,img_flat)) /255
x_test = x_test.reshape((-1,img_flat))/ 255

x_train.shape


60000 train samples
10000 test samples


(60000, 784)

In [220]:
from keras.utils import to_categorical

y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)


y_test.shape

(10000, 10)

In [221]:
from keras.models import Sequential
from keras.layers import Dense, Activation


model = Sequential([
    Dense(units=img_flat, activation='tanh', input_shape=(img_flat,) ),
    Dense(units=10),
    Activation('softmax'),
])

In [226]:
from keras.optimizers import SGD
from keras.losses import categorical_crossentropy
model.compile(loss=categorical_crossentropy,metrics=['accuracy'],
              optimizer=SGD())

In [227]:
model.fit(x_train, y_train,batch_size=100,epochs=26, validation_data=(x_test,y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/26
60000/60000 [==============================] - 5s 84us/step - loss: 0.0922 - acc: 0.9749 - val_loss: 0.1093 - val_acc: 0.9673
Epoch 2/26
60000/60000 [==============================] - 5s 79us/step - loss: 0.0909 - acc: 0.9754 - val_loss: 0.1082 - val_acc: 0.9676
Epoch 3/26
60000/60000 [==============================] - 5s 79us/step - loss: 0.0901 - acc: 0.9756 - val_loss: 0.1075 - val_acc: 0.9676
Epoch 4/26
60000/60000 [==============================] - 5s 80us/step - loss: 0.0893 - acc: 0.9759 - val_loss: 0.1070 - val_acc: 0.9679
Epoch 5/26
60000/60000 [==============================] - 5s 80us/step - loss: 0.0886 - acc: 0.9761 - val_loss: 0.1062 - val_acc: 0.9679
Epoch 6/26
60000/60000 [==============================] - 5s 80us/step - loss: 0.0879 - acc: 0.9763 - val_loss: 0.1063 - val_acc: 0.9677
Epoch 7/26
60000/60000 [==============================] - 5s 84us/step - loss: 0.0872 - acc: 0.9763 - val_loss: 0.1051 - val_acc

In [228]:
y_pred = model.predict(x_test)
y_pred

array([[  3.20973732e-06,   9.61513869e-10,   2.88966203e-05, ...,
          9.98399198e-01,   2.47650987e-05,   5.65931332e-05],
       [  5.90275567e-06,   1.48060601e-04,   9.98668909e-01, ...,
          1.60545649e-13,   1.56897095e-05,   2.27047938e-12],
       [  6.19875834e-07,   9.92289245e-01,   2.11142353e-03, ...,
          9.75647708e-04,   2.82528927e-03,   2.05319637e-04],
       ..., 
       [  2.60039510e-08,   3.90034138e-09,   1.54121878e-07, ...,
          1.64644589e-04,   9.77030955e-04,   2.02654907e-03],
       [  9.07775132e-07,   1.22899303e-06,   8.38915639e-08, ...,
          1.82699978e-07,   1.51265995e-03,   5.90592073e-08],
       [  1.36288159e-04,   5.23765387e-08,   2.15043736e-04, ...,
          7.67588038e-09,   2.55577856e-06,   9.75394414e-07]], dtype=float32)

In [229]:
loss,accuracy = model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

10000/10000 [==============================] - 1s 62us/step
Test loss: 0.0963517405443
Test accuracy: 0.971


In [230]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(x_test)
cm = confusion_matrix(y_true=np.argmax(y_test,axis=1), y_pred=np.argmax(y_pred,axis=1))

print(cm)

[[ 966    0    1    2    0    4    1    4    2    0]
 [   0 1120    3    1    0    1    4    2    4    0]
 [   4    0 1004    3    2    0    4    6    8    1]
 [   0    0    3  987    0    5    0    8    4    3]
 [   1    0    6    1  948    0    5    2    2   17]
 [   7    1    0    9    2  857    8    1    5    2]
 [   6    3    2    0    5    9  929    1    3    0]
 [   1    5   12    2    0    1    0  998    2    7]
 [   4    1    5    9    4    5    4    5  936    1]
 [   5    5    1    9   10    3    0    8    3  965]]
